Repository BurntToaster-Pirate15/Project-Prometheus, pull requests merged in 2024-07, with the labels that each got.

#1 feat: Add a github action which builds the project on every push to the branch
  .github/workflows/godot-ci.yml
  .gitignore
  export_presets.cfg
Labels: needs review, enhancement

#13 Movement: Add both grid based and pixel based movement
  project.godot
  scripts/player.gd
Labels: enhancement, merge when ready

#22 workflow: fix labeller
  .github/workflows/labeller.yml
Labels: merge when ready

#21 UI: make ui buttons work
  project.godot
  scenes/credits.tscn
  scenes/game.tscn
  scenes/main_menu.tscn
  scenes/player.tscn
  scripts/credits.gd
  scripts/menu.gd
Labels: merge when ready

#27 Assets moved
  assets/tilesetV1.png
  assets/tilesetV1.png.import
  project.godot
  tile_map.tscn
Labels: merge when ready
